// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKj1ouVcICfzDEGlkoJ3Byr7IvQOKDwU',
    appId: '1:668450962175:web:a0f7923ffa552f6761eaca',
    messagingSenderId: '668450962175',
    projectId: 'gstamplearningclub',
    authDomain: 'gstamplearningclub.firebaseapp.com',
    storageBucket: 'gstamplearningclub.appspot.com',
    measurementId: 'G-WJ7168M602',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr42ijoAlvbDO6AlfG_KIMAhPPeiM5fP8',
    appId: '1:668450962175:android:266980cc7295b9af61eaca',
    messagingSenderId: '668450962175',
    projectId: 'gstamplearningclub',
    storageBucket: 'gstamplearningclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdw_cxBSkHZzEact_Si9xMfzorO19-sTs',
    appId: '1:668450962175:ios:25e100e15cdcc1ea61eaca',
    messagingSenderId: '668450962175',
    projectId: 'gstamplearningclub',
    storageBucket: 'gstamplearningclub.appspot.com',
    iosBundleId: 'com.example.l6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdw_cxBSkHZzEact_Si9xMfzorO19-sTs',
    appId: '1:668450962175:ios:948c0771141e83b161eaca',
    messagingSenderId: '668450962175',
    projectId: 'gstamplearningclub',
    storageBucket: 'gstamplearningclub.appspot.com',
    iosBundleId: 'com.example.l6.RunnerTests',
  );
}
